[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ascii_arms"
version = "1.0"
dependencies = [
    "colorama",
    "tabulate",
]
requires-python = ">= 3.11"